### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by jsmtl81** [GeorgiKeranov/facebook-marketplace-bot#17]
Hello Georgi ,

 i'm getting suddenly an error and i think beacuse of chrome driver , how can i fix it please .
after the google chrome got updated , i start getting this error and it looks that the driver for the latest chrome version is not yet available on google.

C:\wamp64\www\scripts\fblister\facebook-marketplace-bot>main.py
Traceback (most recent call last):
  File "C:\wamp64\www\scripts\fblister\facebook-marketplace-bot\main.py", line 5, in <module>
    scraper = Scraper('https://facebook.com')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wamp64\www\scripts\fblister\facebook-marketplace-bot\helpers\scraper.py", line 27, in __init__
    self.setup_driver()
  File "C:\wamp64\www\scripts\fblister\facebook-marketplace-bot\helpers\scraper.py", line 55, in setup_driver
    chrome_driver_path = ChromeDriverManager().install()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\http.py", line 33, in get
    self.validate_response(resp)
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zipException ignored in: <function Scraper.__del__ at 0x000001B15F4F5800>
Traceback (most recent call last):
  File "C:\wamp64\www\scripts\fblister\facebook-marketplace-bot\helpers\scraper.py", line 31, in __del__
    self.driver.close()
    ^^^^^^^^^^^
AttributeError: 'Scraper' object has no attribute 'driver'

**Comment by jsmtl81** [comment]
I think this happened after the google chrome got updated to a new version but i'm not sure how to fix it .

**Comment by Youyou9722** [comment]
Upgrade the webdriver manager version.

**Comment by jsmtl81** [comment]
not sure , how it works . my chrome version got updated to 115.0.5790.110 . isn't the chromedriver that should be upgraded ? 
the thing is that the chromedriver for 115.0.5790.110  isn't available yet on google . and i thought about doing a downgrade for google to make it work until the new version of chromedriver will be available . 
sorry not sure what you men by upgrading the webdriver manager , is that for python ?
Thanks for helping out

**Comment by Youyou9722** [comment]
It would be something like that, just update it in your terminal. I’m writing from memory on my phone right now. I think the « web drive manager » part is wrong, just put the right name and it should work. 

pip install --upgrade web-drive-manager

**Comment by GeorgiKeranov** [comment]
Sometimes it happens if the chrome driver version is broken, in this case you can downgrade it manually, in `helpers/scraper.py` -> `"114.0.5735.16"`
<img width="666" alt="Screenshot 2023-08-25 at 12 13 48" src="https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/22518317/bf68f5c6-1604-4205-9841-ffff215f0a44">

**Comment by jsmtl81** [comment]
Hello Georgi , i tried that but the version of chrome i have is more recent so i got this error . I mean if i downgrade the driver , my google chrome sill more recent , could you please check the execution i got Thank you
C:\wamp64\www\scripts\fblister\facebook-marketplace-bot>main.py
Traceback (most recent call last):
  File "C:\wamp64\www\scripts\fblister\facebook-marketplace-bot\main.py", line 5, in <module>
    scraper = Scraper('https://facebook.com')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wamp64\www\scripts\fblister\facebook-marketplace-bot\helpers\scraper.py", line 27, in __init__
    self.setup_driver()
  File "C:\wamp64\www\scripts\fblister\facebook-marketplace-bot\helpers\scraper.py", line 56, in setup_driver
    self.driver = webdriver.Chrome(service=ChromeService(chrome_driver_path), options = self.driver_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\js_mt\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 117.0.5938.92 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00616E73+48323]
        (No symbol) [0x005A9661]
        (No symbol) [0x004B5308]
        (No symbol) [0x004D634C]
        (No symbol) [0x004D2093]
        (No symbol) [0x004D0719]
        (No symbol) [0x00500DF5]
        (No symbol) [0x00500ADC]
        (No symbol) [0x004FA6D6]
        (No symbol) [0x004D847C]
        (No symbol) [0x004D957D]
        GetHandleVerifier [0x0087FD5D+2575277]
        GetHandleVerifier [0x008BF86E+2836158]
        GetHandleVerifier [0x008B96DC+2811180]
        GetHandleVerifier [0x006A41B0+626688]
        (No symbol) [0x005B314C]
        (No symbol) [0x005AF4B8]
        (No symbol) [0x005AF59B]
        (No symbol) [0x005A21B7]
        BaseThreadInitThunk [0x76237BA9+25]
        RtlInitializeExceptionChain [0x77C3B79B+107]
        RtlClearBits [0x77C3B71F+191]

Exception ignored in: <function Scraper.__del__ at 0x0000019389555A80>
Traceback (most recent call last):
  File "C:\wamp64\www\scripts\fblister\facebook-marketplace-bot\helpers\scraper.py", line 31, in __del__
    self.driver.close()
    ^^^^^^^^^^^
AttributeError: 'Scraper' object has no attribute 'driver'

C:\wamp64\www\scripts\fblister\facebook-marketplace-bot>

**Comment by jsmtl81** [comment]
the link where the driver are on google are here https://chromedriver.chromium.org/downloads
but if it is more recent , they are under different location https://googlechromelabs.github.io/chrome-for-testing/#stable
let me know what you think please 
Thanks
